Update mesh.md arrows has been deprecated
It is throwing an error because arrows has been deprecated, 
" arrows!(ax, vertices, p.converted[][1].normal, lengthscale = 0.1, arrowsize = Vec3f(0.05, 0.05, 0.1), color = :orange)
ERROR: MethodError: no method matching getindex(::Observable{GeometryBasics.Mesh{…}}, ::Int64)
The function `getindex` exists, but no method is defined for this combination of argument types."

arrows3d! works fine.
Removed kwd arrowsize as it is also deprecated