compute text + name cleanup (#4945)
* clean up more names and WGLMakie backend code

* initial version of text

* skip arg merge step

* allow benchmarks to run

* reenable ComputePipeline tests

* disable old code

* handle text bounding boxes

* disable precompile partially to get benchmarks

* maybe like this?

* disable less precompiles

* cache glyph and line arrays

* clean up redundant conversions

* reused more args code

* fix compile errors

* minimal changes to make text work in CairoMakie

* remove redundant conversion

* prototype linesegments as child plot

* restore PolarAxis

* update Menu

* fix update to faces not propagating

* update buffers

* get WGLMakie working

* lines

* fix text for new reality

* more clean up

* make text more computegraphy

* try to have positions name positions_transformed_f32c

* Try 1.11 for relocatability (#4944)

* Try 1.11 for relocatability

CI seems to fail due to a weird error:
```julia
  Total artifact file size: 354.322 MiB
┌ Warning: Circular dependency detected.
│ Precompilation will be skipped for dependencies in this cycle:
│  ┌ IntervalArithmetic → IntervalArithmeticRandomExt
│  └─ IntervalArithmetic → IntervalArithmeticLinearAlgebraExt
│ Precompilation will also be skipped for the following, which depend on the above cycle:
│   IntervalArithmetic → IntervalArithmeticSparseArraysExt
│   MakieApp
│   ExactPredicates
│   CairoMakie
│   DelaunayTriangulation
│   IntervalArithmetic → IntervalArithmeticIntervalSetsExt
│   Makie
└ @ Pkg.API.Precompilation /opt/hostedtoolcache/julia/1.10.9/x64/share/julia/stdlib/v1.10/Pkg/src/precompilation.jl:583
Precompiling packages...
   1859.9 ms  ✓ IntervalArithmetic
   2432.1 ms  ✓ MakieCore
  2 dependencies successfully precompiled in 4 seconds. 232 already precompiled. 9 skipped due to circular dependency.
- PackageCompiler: compiling incremental system image
┌ Error: Error during loading of extension IntervalArithmeticLinearAlgebraExt of IntervalArithmetic, use `Base.retry_load_extensions()` to retry.
│   exception = 1-element ExceptionStack:
LoadError: could not load symbol "openblas_set_num_threads64_":
/opt/hostedtoolcache/julia/1.10.9/x64/bin/julia: undefined symbol: openblas_set_num_threads64_
Stacktrace:
  [1] top-level scope
    @ ~/.julia/packages/IntervalArithmetic/XjBhk/ext/IntervalArithmeticLinearAlgebraExt.jl:9
  [2] include(mod::Module, _path::String)
    @ Base ./Base.jl:495
  [3] _require(pkg::Base.PkgId, env::Nothing)
    @ Base ./loading.jl:2084
  [4] __require_prelocked(uuidkey::Base.PkgId, env::Nothing)
    @ Base ./loading.jl:1882
  [5] #invokelatest#2
    @ ./essentials.jl:892 [inlined]
  [6] invokelatest
    @ ./essentials.jl:889 [inlined]
  [7] _require_prelocked
    @ ./loading.jl:1875 [inlined]
  [8] _require_prelocked
    @ ./loading.jl:1872 [inlined]
  [9] run_extension_callbacks(extid::Base.ExtensionId)
    @ Base ./loading.jl:1365
 [10] run_extension_callbacks(pkgid::Base.PkgId)
    @ Base ./loading.jl:1400
 [11] run_package_callbacks(modkey::Base.PkgId)
    @ Base ./loading.jl:1224
 [12] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1889
 [13] #invokelatest#2
    @ ./essentials.jl:892 [inlined]
 [14] invokelatest
    @ ./essentials.jl:889 [inlined]
 [15] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1875
 [16] macro expansion
    @ ./loading.jl:1860 [inlined]
 [17] macro expansion
    @ ./lock.jl:267 [inlined]
 [18] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1823
 [19] #invokelatest#2
    @ ./essentials.jl:892 [inlined]
 [20] invokelatest
    @ ./essentials.jl:889 [inlined]
 [21] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1818
 [22] include(mod::Module, _path::String)
    @ Base ./Base.jl:495
 [23] include(x::String)
    @ ExactPredicates ~/.julia/packages/ExactPredicates/fhcrS/src/ExactPredicates.jl:4
 [24] top-level scope
    @ ~/.julia/packages/ExactPredicates/fhcrS/src/ExactPredicates.jl:8
 [25] include(mod::Module, _path::String)
    @ Base ./Base.jl:495
 [26] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:2084
 [27] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1882
 [28] #invokelatest#2
    @ ./essentials.jl:892 [inlined]
 [29] invokelatest
    @ ./essentials.jl:889 [inlined]
 [30] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1875
 [31] macro expansion
    @ ./loading.jl:1860 [inlined]
 [32] macro expansion
    @ ./lock.jl:267 [inlined]
 [33] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1823
 [34] #invokelatest#2
    @ ./essentials.jl:892 [inlined]
 [35] invokelatest
    @ ./essentials.jl:889 [inlined]
 [36] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1818
--- the last 12 lines are repeated 4 more times ---
 [85] top-level scope
    @ /tmp/jl_6DojWJgzqB:14
 [86] include(mod::Module, _path::String)
    @ Base ./Base.jl:495
 [87] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:323
in expression starting at /home/runner/.julia/packages/IntervalArithmetic/XjBhk/ext/IntervalArithmeticLinearAlgebraExt.jl:1
└ @ Base loading.jl:1371
```

* Update relocatability.yml

* Update relocatability.yml

* Update relocatability.yml

* fix WGLMakie

* those dont work yet

* fix most text issues (no latex/rich yet)

* Move most of the texture atlas logic to JS, to be able to use bigger atlas (#4942)

* move most of the texture atlas logic to JS, to be able to use bigger atlasses without uploading 20mb for every plot

* fix some more problems

* fix remaining problems

* fix precompiles

* properly map offset to origins

* fix order issue

* add changelog and update test for new return type

* fix 3d rotation

* fix missing glyphs

* clean up glyph_data and fix last test fail

* add tests to check if js atlas is pixel perfect

* add marker

* avoid +- 0.5

* integrate test

* fix test

---------

Co-authored-by: ffreyer <frederic481994@hotmail.de>

* fix per-string offsets

* fix PolarAxis errors

* restore position attribute handling

* fix renaming

* recover the small marker fix

* refactor scatter to be more reusable

* fix linesegments

* refactor CairoMakie text

* fix linewidth

* fix WGLMakie

* fix WGLMakie

* remove unused function

---------

Co-authored-by: SimonDanisch <sdanisch@protonmail.com>